### ISSUE TITLE
KeyError: 'outConL'

### ISSUE THREAD

**Issue by bc-maritn** [TheRealMurmel/py-bahn-api#1]
When I run main.py I get:

```
sampleStationSearch
('Frankfurt(Main)Hbf', '8000105')
('FRANKFURT(MAIN)', '8096021')
('Frankfurt(M)Flughafen', '8000281')
('Frankfurt(M) Flughafen Fernbf', '8070003')
('Frankenthal Hbf', '8000332')
('Frankfurt(Main)Süd', '8002041')
('Frankfurt(Main)West', '8002042')
('Frankfurt(Oder)', '8010113')
('Frankfurt-Niederrad', '8002050')
('Frankfurt(M)Konstablerwache', '8004429')
('Frankfurt-Höchst', '8000106')
('Frankfurt(Main)-Gateway Gardens', '8002060')
('Frankfurt(M) Flughafen Regionalbf', '8070004')
('Frankfurt(Main)Ost', '8002039')
('Frankfurt-Höchst Farbwerke', '8002051')
('Frankenthal Süd', '8002025')
('Frankfurt-Mainkur', '8002048')
('Frankfurt(M)Galluswarte', '8006690')
('Frankfurt(M)Lokalbahnhof', '8002038')
('Frankenthal-Flomersh', '8002014')
('Frankfurt-Sossenheim', '8002054')
('Frankfurt(M)Stresemannallee', '8002059')
('Frankfurt am Main - Stadion', '8002040')
('Frankfurt-Griesheim', '8002046')
('Frankfurt-Nied', '8002049')

sampleConnectionSearch
Traceback (most recent call last):
  File "/home/martin/.p2/pool/plugins/org.python.pydev.core_12.0.0.202402010911/pysrc/pydevd.py", line 3616, in <module>
    main()
  File "/home/martin/.p2/pool/plugins/org.python.pydev.core_12.0.0.202402010911/pysrc/pydevd.py", line 3609, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/martin/.p2/pool/plugins/org.python.pydev.core_12.0.0.202402010911/pysrc/pydevd.py", line 2626, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/martin/.p2/pool/plugins/org.python.pydev.core_12.0.0.202402010911/pysrc/pydevd.py", line 2634, in _exec
    globals = pydevd_runpy.run_path(file, globals, '__main__')
  File "/home/martin/.p2/pool/plugins/org.python.pydev.core_12.0.0.202402010911/pysrc/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/martin/.p2/pool/plugins/org.python.pydev.core_12.0.0.202402010911/pysrc/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/martin/.p2/pool/plugins/org.python.pydev.core_12.0.0.202402010911/pysrc/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/martin/Nextcloud portknox/2024-02--Bahn-Preissuche/py-bahn-api-main/main.py", line 84, in <module>
    main()
  File "/home/martin/Nextcloud portknox/2024-02--Bahn-Preissuche/py-bahn-api-main/main.py", line 78, in main
    sampleConnectionSearch()
  File "/home/martin/Nextcloud portknox/2024-02--Bahn-Preissuche/py-bahn-api-main/main.py", line 38, in sampleConnectionSearch
    connections = [(connection['cid'], connection['ctxRecon']) for connection in connectionsResponse['svcResL'][0]['res']['outConL']]
KeyError: 'outConL'

```

**Comment by bc-maritn** [comment]
There's an error message in the data: "HAFAS Kernel: Date outside of the timetable period."
